"""initial_schema

Revision ID: 35b692510394
Revises: 
Create Date: 2026-08-01 20:31:02.447250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b692510394'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_uuid'), table_name='facturas')
    op.create_index(op.f('ix_facturas_uuid'), 'facturas', ['uuid'], unique=False)
    op.create_unique_constraint('uq_facturas_empresa_uuid', 'facturas', ['empresa_id', 'uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_facturas_empresa_uuid', 'facturas', type_='unique')
    op.drop_index(op.f('ix_facturas_uuid'), table_name='facturas')
    op.create_index(op.f('ix_facturas_uuid'), 'facturas', ['uuid'], unique=True)
    # ### end Alembic commands ###
